<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sieve</string>
	</array>
	<key>name</key>
	<string>Sieve</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(stop|require)\b</string>
			<key>name</key>
			<string>keyword.control.flow.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|elsif|else)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:(is|contains|matches)</string>
			<key>name</key>
			<string>keyword.operator.comparison.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:(under|over)</string>
			<key>name</key>
			<string>keyword.operator.relational.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:[a-zA-z][a-zA-Z0-9]*</string>
			<key>name</key>
			<string>declaration.tag.sive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(allof|anyof|exists)\b</string>
			<key>name</key>
			<string>keyword.operator.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\d[K|M|G]?)</string>
			<key>name</key>
			<string>constant.numeric.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.boolean.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(header|address|envelope|size)\b</string>
			<key>name</key>
			<string>constant.language.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(removeflag|setflag|addflag)\b</string>
			<key>name</key>
			<string>support.function.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(keep|discard|fileinto|redirect|reject)\b</string>
			<key>name</key>
			<string>entity.name.class.sieve</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(["])</string>
			<key>end</key>
			<string>([^\\]\1)</string>
			<key>name</key>
			<string>string.quoted.sieve</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>text:\n</string>
			<key>end</key>
			<string>(^\.$)</string>
			<key>name</key>
			<string>string.multiline.sieve</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment.line.hash.sieve</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.sieve</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>comment.block.content.sieve</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sieve</string>
	<key>uuid</key>
	<string>46d1afcd-26c2-43d2-bfd4-8e271852e513</string>
</dict>
</plist>
